steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tw-stock-simulator:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tw-stock-simulator:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - tw-stock-simulator
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tw-stock-simulator:$COMMIT_SHA
      - --region=${_REGION}
      - --service-account=${_RUNTIME_SERVICE_ACCOUNT}
      - --set-env-vars=SIMULATION_ENV=staging,GCS_BUCKET=${_GCS_BUCKET},RUN_MODE=tick,CANDIDATE_SNAPSHOT_URL=${_CANDIDATE_SNAPSHOT_URL}
      - --tasks=1
      - --max-retries=0
      - --task-timeout=55s
      - --cpu=1
      - --memory=512Mi
substitutions:
  _REGION: asia-east1
  _REPOSITORY: tw-stock
  _GCS_BUCKET: project-aef205b5-5c27-4084-94c-tw-stock-data
  _RUNTIME_SERVICE_ACCOUNT: tw-stock-runtime@project-aef205b5-5c27-4084-94c.iam.gserviceaccount.com
  _CANDIDATE_SNAPSHOT_URL: https://script.google.com/macros/s/AKfycbxMSe1WvXNjTbAzxZSP8mD_9wt11BIGQSyaFTktoet_v7WQ1KujUu19pflwS6zHfhqt/exec
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/tw-stock-simulator:$COMMIT_SHA'
